### ISSUE TITLE
ENV issue

### ISSUE THREAD

**Issue by LijieTu** [Kaixhin/dockerfiles#3]
ENV PATH=/root/torch/install/bin:$PATH 
should be ENV PATH /root/torch/install/bin:$PATH 
in dockerfiles/cuda-torch-plus/Dockerfile

See here https://github.com/zeromq/jzmq/commit/5558dc0ff35ae1e5daa80983aee3c2eeb16f720c

**Comment by Kaixhin** [comment]
According to the documentation on [Dockerfiles](https://docs.docker.com/reference/builder/#env), this should be fine (and I like to use the = for consistency even if only one ENV variable is set).

If you are getting an error it's probably because of an error introduced in https://github.com/Kaixhin/dockerfiles/commit/71774d47bca11016195784809580e7e02acb0026, which should hopefully be resolved. Once the Docker image is rebuilt please try again.

**Comment by Kaixhin** [comment]
I've sorted out paths in the dependencies and tested `fbcunn` within the `cuda-torch-plus` image, so I'm now closing this issue.
