### ISSUE TITLE
Official docker image & multi-arch

### ISSUE THREAD

**Issue by vaibhavsood** [Kaixhin/dockerfiles#37]
Hi, 

Want to check if there are any plans to make these docker images official? The steps for doing that are as per here: https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

Eventually I am interested in creating and publishing multi-arch images on dockerhub (especially for ppc64le), as described here https://github.com/docker-library/official-images#multiple-architectures, the first step for that is to have an official Intel image on dockerhub

**Comment by Kaixhin** [comment]
These images will not be made official, as it requires a level of commitment that I cannot provide. Furthermore, many newer frameworks have their own official images nowadays. It is better for maintainers of the frameworks to do this, as active development has broken some of the Dockerfiles in this repo, and I don't have the time to keep fixing all of these.

It appears that there are solutions for [building on different architectures](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/) without requiring official images, so that is an option. You are welcome to take any of the material from this repo, submit and maintain official images yourself, or simply do your own personal builds.
