### ISSUE TITLE
Add documentation for cuda-caffe

### ISSUE THREAD

**Issue by dreamflasher** [Kaixhin/dockerfiles#40]
When running `nvidia-docker run -it kaixhin/cuda-caffe:8.0` one ends up in a ~/caffe folder. But caffee seems not to be available via caffe command. Also it looks like that caffe is actually not built. How is one supposed to use this image?

**Comment by Kaixhin** [comment]
The Caffe documentation is [here](http://caffe.berkeleyvision.org/). The `caffe` binary is at `./build/install/bin/caffe` (assuming the current directory is `~/caffe`). `$CAFFE_ROOT` isn't set because you're placed in `~/caffe` by default. I've just downloaded the image and gone through the [LeNet/MNIST tutorial](http://caffe.berkeleyvision.org/gathered/examples/mnist.html) on GPU, so can confirm that it Caffe is installed correctly.
