### ISSUE TITLE
could not find boost

### ISSUE THREAD

**Issue by Hiker01** [Kaixhin/dockerfiles#45]
When I make other caffe with your  enviroment, I got this error. Can you tell me where did you put your boost library?

**Comment by Kaixhin** [comment]
In order to make automated builds on the Docker Hub that would run within the compute limits, many Dockerfiles have been split (note that I stopped these a long time ago due to a further reduction in limits). You can get the first part of the Caffe container from [here](https://github.com/Kaixhin/dockerfiles/blob/master/caffe/deps/Dockerfile#L13) (with the Boost dependency highlighted).
