### ISSUE TITLE
Question: how do you recommend installing CUDA on the host OS?

### ISSUE THREAD

**Issue by tleyden** [Kaixhin/dockerfiles#6]
I ran into [an issue](https://groups.google.com/d/msg/torch7/yCSNIzW590M/Af7CHXEdDQAJ) with a minor mismatch in the CUDA versions if I installed CUDA on the host using [these instructions](https://gist.github.com/tleyden/ce49daba0478b496037f) and then trying to run the [kaixhin/cuda](https://hub.docker.com/r/kaixhin/cuda/~/dockerfile/) docker image.

Any advice here?

**Comment by Kaixhin** [comment]
With 221dd24 I added a note to the [CUDA section](https://github.com/Kaixhin/dockerfiles#cuda) of the README which notes that the recommended way of installing the right driver version is to use the `.run` file (so that people don't have to always update their driver when new images are built / the `.run` files have been in my experience more reliable). I've also added a link to this from every single current CUDA-based Dockerfile, so people will always be linked to the most up-to-date information. If you have any additions to the instructions then please let me know, or otherwise close this issue.

As mentioned in https://github.com/Kaixhin/dockerfiles/issues/7#issuecomment-159085882, this driver mismatch will be sorted once NVIDIA release their official images with their Docker plugin.

**Comment by tleyden** [comment]
Thanks!  I think this answers my question, so I'll close the issue.

One follow up question:

> once NVIDIA release their official images with their Docker plugin.

Isn't that already available here?

https://github.com/NVIDIA/nvidia-docker

(I was notified about this, but haven't had a chance to actually look at it too closely)

**Comment by Kaixhin** [comment]
I suggest looking at the currently open issues for more details but this is still in the experimental stage. Right now they rely on a shell script which acts as a wrapper for Docker; the proper way to interact with Docker is to write a Docker plugin, which they are developing now. Once that is ready then they will probably be ready to do an official release on the Docker Hub, which I can then use as my base CUDA image for the various machine learning images.

**Comment by victorhcm** [comment]
Hey @Kaixhin, it seems NVIDIA has released a plugin and the CUDA images:
- [Images](https://hub.docker.com/r/nvidia/cuda/)
- [Plugin](https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker-plugin)

I ran a small test, and it seems to be working fine. I thought that it could work out-of-the-box with your CUDA images, but unfortunetely it doesn't. I'm wondering if it is already mature enough to update our images.

**Comment by Kaixhin** [comment]
@victorhcm Actually I think I got it working with `kaixhin/cuda-torch`, but I haven't tested it extensively. I've tried to set everything up in the [`nvidia` branch](https://github.com/Kaixhin/dockerfiles/tree/nvidia), and I'm basically waiting for an actual release (as they should be leaving beta soon; see https://github.com/NVIDIA/nvidia-docker/issues/82).
